### ISSUE TITLE
Bildersuche

### ISSUE THREAD

**Issue by MrMoeNr1YT** [LamboLaure/Git#1]
Laurence muss alle 5 bilder suchen

**Comment by LamboLaure** [comment]
pictures found 
https://www.google.com/url?sa=i&url=https%3A%2F%2Fstudyflix.de%2Fallgemeinwissen%2F5-saeulen-des-islam-5992&psig=AOvVaw1US6cXRJ9HfbnArDXOSxPa&ust=1706478260747000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCOC61YXF_oMDFQAAAAAdAAAAABAJ
